# configs/EB-Navigation.yaml
model_name: MODEL_NAME
model_type: era
down_sample_ratio: 1
language_only: False
eval_sets: ['base']
chat_history: False
n_shots: 0
detection_box: False
multistep: False
resolution: 500
exp_name: eval
env_feedback: True
tp: 1