# configs/EB-Navigation.yaml
model_name: MODEL_NAME
model_type: era
down_sample_ratio: 1
language_only: 0
eval_sets: ['base']
chat_history: 0
n_shots: 0
multiview: 0
detection_box: 1
multistep: 0
resolution: 500
visual_icl: 0
tp: 1