a = [
    'find a Cart', 'find a Potato', 'find a Faucet', 'find a Ottoman', 'find a CoffeeMachine',
    'find a Candle', 'find a CD', 'find a Pan', 'find a Watch', 'find a HandTowel',
    'find a SprayBottle', 'find a BaseballBat', 'find a CellPhone', 'find a Kettle',
    'find a Mug', 'find a StoveBurner', 'find a Bowl', 'find a Toilet', 'find a DiningTable',
    'find a Spoon', 'find a TissueBox', 'find a Shelf', 'find a Apple', 'find a TennisRacket',
    'find a SoapBar', 'find a Cloth', 'find a Plunger', 'find a FloorLamp', 'find a ToiletPaperHanger',
    'find a CoffeeTable', 'find a Spatula', 'find a Plate', 'find a Bed', 'find a Glassbottle',
    'find a Knife', 'find a Tomato', 'find a ButterKnife', 'find a Dresser', 'find a Microwave',
    'find a CounterTop', 'find a GarbageCan', 'find a WateringCan', 'find a Vase', 'find a ArmChair',
    'find a Safe', 'find a KeyChain', 'find a Pot', 'find a Pen', 'find a Cabinet', 'find a Desk',
    'find a Newspaper', 'find a Drawer', 'find a Sofa', 'find a Bread', 'find a Book',
    'find a Lettuce', 'find a CreditCard', 'find a AlarmClock', 'find a ToiletPaper',
    'find a SideTable', 'find a Fork', 'find a Box', 'find a Egg', 'find a DeskLamp',
    'find a Ladle', 'find a WineBottle', 'find a Pencil', 'find a Laptop', 'find a RemoteControl',
    'find a BasketBall', 'find a DishSponge', 'find a Cup', 'find a SaltShaker', 'find a PepperShaker',
    'find a Pillow', 'find a Bathtub', 'find a SoapBottle', 'find a Statue', 'find a Fridge',
    'find a Sink', 'pick up the KeyChain', 'pick up the Potato', 'pick up the Pot', 'pick up the Pen',
    'pick up the Candle', 'pick up the CD', 'pick up the Pan', 'pick up the Watch',
    'pick up the Newspaper', 'pick up the HandTowel', 'pick up the SprayBottle',
    'pick up the BaseballBat', 'pick up the Bread', 'pick up the CellPhone', 'pick up the Book',
    'pick up the Lettuce', 'pick up the CreditCard', 'pick up the Mug', 'pick up the AlarmClock',
    'pick up the Kettle', 'pick up the ToiletPaper', 'pick up the Bowl', 'pick up the Fork',
    'pick up the Box', 'pick up the Egg', 'pick up the Spoon', 'pick up the TissueBox',
    'pick up the Apple', 'pick up the TennisRacket', 'pick up the Ladle', 'pick up the WineBottle',
    'pick up the Cloth', 'pick up the Plunger', 'pick up the SoapBar', 'pick up the Pencil',
    'pick up the Laptop', 'pick up the RemoteControl', 'pick up the BasketBall',
    'pick up the DishSponge', 'pick up the Cup', 'pick up the Spatula', 'pick up the SaltShaker',
    'pick up the Plate', 'pick up the PepperShaker', 'pick up the Pillow', 'pick up the Glassbottle',
    'pick up the SoapBottle', 'pick up the Knife', 'pick up the Statue', 'pick up the Tomato',
    'pick up the ButterKnife', 'pick up the WateringCan', 'pick up the Vase',
    'put down the object in hand', 'drop the object in hand', 'open the Safe', 'close the Safe',
    'open the Laptop', 'close the Laptop', 'open the Fridge', 'close the Fridge', 'open the Box',
    'close the Box', 'open the Microwave', 'close the Microwave', 'open the Cabinet',
    'close the Cabinet', 'open the Drawer', 'close the Drawer', 'turn on the Microwave',
    'turn off the Microwave', 'turn on the DeskLamp', 'turn off the DeskLamp',
    'turn on the FloorLamp', 'turn off the FloorLamp', 'turn on the Faucet', 'turn off the Faucet',
    'slice the Potato', 'slice the Lettuce', 'slice the Tomato', 'slice the Apple', 'slice the Bread',
    'find a Cabinet_2', 'find a Cabinet_3', 'find a Cabinet_4', 'find a HandTowelHolder_2',
    'find a SinkBasin_2', 'open the Cabinet_2', 'close the Cabinet_2', 'open the Cabinet_3',
    'close the Cabinet_3', 'open the Cabinet_4', 'close the Cabinet_4', 'find a Candle_2',
    'find a Candle_3', 'find a Cloth_2', 'find a SoapBar_2', 'find a SoapBottle_2',
    'find a ToiletPaper_2'
]

print(len(a))